### ISSUE TITLE
Website updates proposal

### ISSUE THREAD

**Issue by vcoisne** [src-d/landing#376]
In order to refocus our messaging around source{d} Engine, I propose the following changes on the website

- [ ] New header navigation menu

- Why source{d}? [New]
- source{d} Engine
- Resources [new]
   - Blog
   - Forum
   - Docs (Move under Resources)
   - Playground
  - Codebase Analysis (Kubernetes, Tensorflow, etc)
- Community
   - Open Source (Moved under community)
- Company

- [ ] Take source{d} Lookout page down for now and move it under prrojects on the Open Source page

On  https://sourced.tech/engine/ 

- [ ] Make it clear that the card with the questions are clickable to access the actual queries 

- [ ] Add logo of languages that are supported

**Comment by marnovo** [comment]
@src-d/applications just to avoid confusion I'm closing this now and moving it to https://github.com/src-d/feature-idea/issues/141. Since some of these are major things we're drafting this first and will go through the regular feature-idea -> backlog -> tasks workflow. We'll be still working with Zuri on this.
